/*
*
*
*
*
*
*       DO NOT EDIT THIS FILE
*       For FCC testing purposes!
*
*
*
*
*
*/

"use strict";

const cors = require("cors");
const fs = require("fs");
const runner = require("../test-runner");

module.exports = function (app) {
  app.route("/_api/server.js").get(function (req, res, next) {
    console.log("requested");
    fs.readFile(__dirname + "/../server.js", function (err, data) {
      if (err) return next(err);
      res.send(data.toString());
    });
  });

  app
    .route("/_api/routes/api.js")
    .get(function (req, res, next) {
      console.log("requested");
      fs.readFile(__dirname + "/../routes/api.js", function (err, data) {
        if (err) return next(err);
        res.type("txt").send(data.toString());
      });
    });

  let error;
  app.get("/_api/get-tests", cors(), function (req, res, next) {
    if (!runner.report) runner.run();
    res.json(runner.report);
  });

  app.get("/_api/app-info", function (req, res) {
    let hs = res.getHeaders();
    let h = {};
    Object.keys(hs).forEach(function (k) {
      h[k] = hs[k];
    });
    delete h["access-control-allow-origin"];
    res.json({ headers: h });
  });
};
